UNIkeEN/SJMCL

README.md, docs/README.zh-Hans.md, docs/README.zh-Hant.md
=> docs(README): add zh-Hant readme

src/pages/settings/appearance.tsx
> - e.g. close #xxxx, fix #176 
=> fix(frontend): fix image selection affecting size and resolution

src-tauri/src/instance/commands.rs, src-tauri/src/instance/helpers/misc.rs, src-tauri/src/instance/helpers/mod_loader.rs, src-tauri/src/instance/helpers/mods/forge.rs, src-tauri/src/instance/models/misc.rs, src-tauri/src/launch/commands.rs, src-tauri/src/launch/helpers/command_generator.rs, src-tauri/src/launch/helpers/file_validator.rs, src-tauri/src/launch/models.rs, src-tauri/src/lib.rs, src-tauri/src/tasks/download.rs, src/contexts/task.tsx, src/contexts/toast.tsx, src/locales/en.json, src/locales/zh-Hans.json, src/models/instance/misc.ts, src/pages/downloads.tsx, src/services/instance.ts
=> feat(instance): complete Forge and NeoForge final installation

src-tauri/src/launcher_config/helpers/misc.rs, src-tauri/src/launcher_config/models.rs, src-tauri/src/resource/helpers/misc.rs, src-tauri/src/utils/web.rs, src/models/config.ts
close #611 
`is_china_mainland_ip` 我在保存完没有调用 save，我认为这个量没必要写回？（所以更没必要实时 save）
=> feat(backend): update china(mainland) ip flag in config state to auto select priority source list

src/locales/en.json, src/locales/zh-Hans.json, src/utils/game-error.ts
=> feat(game-error): add native library arch incompatible error notice

src/locales/en.json, src/locales/zh-Hans.json
> fix #720 
> - add missing translation for NoSource state in discover page
=> fix(i18n): add missing translation for NoSource state in discover page

src-tauri/src/utils/web.rs
> - modify user-agent to comply with BMCLAPI requirements
> - modify user-agent to comply with BMCLAPI requirements
=> fix(backend): modify user-agent to comply with BMCLAPI requirements

src/components/modals/download-specific-resource-modal.tsx, src/components/modals/mod-info-modal.tsx, src/components/resource-downloader.tsx
close #734
修复了一个非常低级的问题，天知道当时是干嘛去了而且居然还没测出来
None
=> fix(frontend): recommend mod based on version rather than major version

src-tauri/src/tasks/commands.rs, src-tauri/src/tasks/monitor.rs, src/components/modals/create-instance-modal.tsx, src/components/modals/download-game-server-modal.tsx, src/contexts/task.tsx, src/locales/en.json, src/locales/zh-Hans.json
related  #727 
创建任务成功统一使用 emit event 唤起 toast，而不是作为各个下载命令的 success 自行处理
=> refactor(task): send success created task group event to call toast

src/components/modals/launch-process-modal.tsx, src/utils/response.ts
=> fix(frontend): add user friendly error details when missing locale key or enum map

src/pages/standalone/game-log.tsx
=> fix(frontend): detect 错误 in log messages and classify as ERROR level

src-tauri/assets/game/natives.json, src-tauri/src/instance/commands.rs, src-tauri/src/launch/commands.rs
> - #351 
> - Only repair native lib at startup and don't save. 
> - replace jna lib on mac
=> fix(launch): amend repair native libraried at launching process w/o save

src-tauri/src/tasks/commands.rs, src-tauri/src/tasks/events.rs, src-tauri/src/tasks/monitor.rs, src-tauri/src/tasks/streams/desc.rs, src/contexts/task.tsx, src/models/task.ts
=> fix(task): group status lost when refreshing frontend

src/components/special/global-event-handler.tsx, src/contexts/global-data.tsx, src/contexts/toast.tsx
部分修复 #667，减少发生概率
修复前，每次 DOM 树更新都会触发 listener 重新启动监听，浪费性能。
修复方法：
通过分析两次渲染时改变的依赖对象，追踪来源，并依据 React 最佳实践进行优化：
- 对于常量，套上 `useMemo`
- 对于函数，套上 `useCallback`
修复后，由于程序中的 listener 都是全局的，因此操作 UI 不会再重新监听。
=> perf(frontend): fix the objects that unnecessarily change during rendering

src/components/modals/download-modpack-modal.tsx, src/components/modals/download-resource-modal.tsx, src/components/modals/spotlight-search-modal.tsx, src/components/resource-downloader.tsx, src/locales/en.json, src/locales/zh-Hans.json
#664
先不关 issue，还有远期规划没完成
如标题所示
None
=> feat(resource): add resource search to spotlight search

src-tauri/src/launch/helpers/command_generator.rs, src/locales/en.json, src/locales/zh-Hans.json, src/locales/zh-Hant.json
=> feat(launch): add compatibility with HMCL's custom jvm arg

src/components/modals/delete-instance-alert-dialog.tsx, src/contexts/instance.tsx
=> fix(frontend); fix summary get and route error after deleting instance

src-tauri/src/launch/commands.rs, src-tauri/src/launch/helpers/process_monitor.rs
=> feat(launch): move game log files to a spceific cache folder

src/components/instance-widgets.tsx, src/pages/settings/appearance.tsx
=> fix(frontend): prevent line wrap in instance basic info widget

src-tauri/src/launch/commands.rs, src-tauri/src/launch/helpers/command_generator.rs, src-tauri/src/launch/models.rs
=> feat(launch): support export full command launch script in crash-info zip

src/components/instance-widgets.tsx, src/components/mod-loader-cards.tsx, src/components/modals/create-instance-modal.tsx, src/components/modals/download-specific-resource-modal.tsx, src/components/resource-downloader.tsx, src/components/special/shared-modals-provider.tsx
close #774 
close #780 
close #781 
=> fix(frontend): optimize some UX in resource downloading, refactor some code

src-tauri/src/launch/commands.rs, src-tauri/src/launch/helpers/command_generator.rs, src/components/instance-widgets.tsx, src/components/modals/launch-process-modal.tsx, src/pages/instances/details/[id]/screenshots.tsx, src/services/launch.ts
=> feat(launch): support quick singleplayer launch via parameter

src/pages/instances/details/[id]/worlds.tsx
=> feat(frontend): show per-server BeatLoader during connectivity check

src-tauri/src/launch/helpers/command_generator.rs
=> hotfix(launch): hotfix duplicate quick play options in client jvm args

.github/workflows/build.yml, .github/workflows/sign-macos.yml, .github/workflows/update_version_list.yml
Fix codescan alerts #1-#3
add permissions to action files
None
=> fix(ci/cd): add permissions to action files

src/utils/partial.ts
> - Fixes: https://github.com/UNIkeEN/SJMCL/security/code-scanning/4
=> fix(frontend): prevent prototype pollution in updateByKeyPath

src-tauri/src/launch/helpers/file_validator.rs, src-tauri/src/launcher_config/models.rs
close #798 
> - feat(launch): use future to concurrently speed up file checking.
=> feat(launch): use future to concurrently speed up file checking

src/components/game-version-selector.tsx, src/components/mod-loader-selector.tsx
> - close #818 
> -  enable click on OptionItem to toggle version of game or modLoader, adding to user convenience
=> feat(frontend): enable click on OptionItem to toggle version of game or modLoader

src-tauri/src/launch/commands.rs, src-tauri/src/launch/helpers/process_monitor.rs
fix #458
Fix custom window title persistence with polling thread.
None
=> fix(backend): custom window title persistence

src-tauri/src/account/commands.rs, src-tauri/src/account/helpers/authlib_injector/common.rs, src-tauri/src/account/helpers/authlib_injector/oauth.rs, src-tauri/src/account/helpers/authlib_injector/password.rs, src-tauri/src/launcher_config/commands.rs, src/components/modals/launch-process-modal.tsx
=> fix(account): fail to join in server because of outdated access token

src-tauri/src/instance/commands.rs, src-tauri/src/instance/helpers/loader/common.rs, src-tauri/src/instance/helpers/loader/fabric.rs, src-tauri/src/resource/helpers/modrinth/mod.rs
=> feat(backend): auto download fabric api mod when create instance with fabric

.github/workflows/build.yml
None
Now the nightly and release workflows will produce windows_aarch64 artifacts
None
=> feat(ci/cd): add windows arm64

src-tauri/src/account/commands.rs, src-tauri/src/account/constants.rs, src-tauri/src/account/helpers/authlib_injector/common.rs, src-tauri/src/account/helpers/authlib_injector/models.rs, src-tauri/src/account/helpers/authlib_injector/oauth.rs, src-tauri/src/account/helpers/microsoft/constants.rs, src-tauri/src/account/helpers/microsoft/oauth.rs, src-tauri/src/account/helpers/misc.rs, src-tauri/src/account/models.rs, src/components/modals/add-player-modal.tsx, src/components/modals/relogin-player-modal.tsx, src/models/account.ts, src/services/account.ts
=> fix & refactor(account): fix device auth resp parse error; update stucture and simplify codes

src/locales/en.json, src/locales/zh-Hans.json, src/locales/zh-Hant.json, src/pages/downloads.tsx, src/utils/task.ts
=> feat(task): update retry task name parse logic to be able to trigger later events

src/components/modals/add-player-modal.tsx
=> fix(frontend): reset states on select player modal close

CHANGELOG.md, docs/CHANGELOG.zh-Hans.md
=> docs(changelog): add latest changelog

src-tauri/src/instance/helpers/client_json.rs, src-tauri/src/instance/helpers/misc.rs
> - fix #789
> - add detection of PCL instance loader
=> feat(instance): add detection of PCL instance loader

src-tauri/src/instance/helpers/loader/forge.rs
=> fix(instance): legacy forge libraries download incomplete

src-tauri/src/launch/helpers/command_generator.rs
=> fix(launch): mask access token from leakage during exportation

src-tauri/src/launcher_config/helpers/java.rs
=> feat(instance): improve detection of Java list

src/components/modals/mod-info-modal.tsx
=> fix(frontend): add close button to mod info modal

src-tauri/src/launcher_config/commands.rs, src-tauri/src/launcher_config/helpers/misc.rs, src-tauri/src/launcher_config/helpers/updater.rs, src-tauri/src/launcher_config/models.rs, src-tauri/src/lib.rs, src/components/modals/notify-new-version-modal.tsx, src/models/config.ts, src/services/config.ts
=> fix(updater): use GitHub first outside China mainland, fix version number in dev mode

src-tauri/src/launch/commands.rs, src-tauri/src/launch/helpers/command_generator.rs, src-tauri/src/launch/helpers/process_monitor.rs, src-tauri/src/utils/mod.rs, src-tauri/src/utils/shell.rs
> - close #899
> - feat(backend): support advanced game config
=> feat(backend): support advanced game config

.github/workflows/test.yml
=> fix(ci/cd): add rustfmt component during rust installing in the actions to resolve lint issue

docs/README.zh-Hans.md, src/contexts/routing-history.tsx
=> fix(frontend): fix routing error across instance detail pages

LICENSE.EXTRA, README.md, docs/README.zh-Hans.md, docs/README.zh-Hant.md
=> docs(license): update additional terms for adding preset auth servers

.env.template, .github/copilot-instructions.md, .github/workflows/build.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/test.yml, src-tauri/src/account/helpers/microsoft/oauth.rs
=> fix(account): remove Microsoft client secret from env

src/components/common/editable.tsx, src/components/common/option-item.tsx
=> fix: again fix long text behavior

src/pages/launch.tsx
=> fix(frontend): fix text ellipsis issue of player switch button on launch page

src/components/common/editable.tsx
=> fix(frontend): align texts to the right in Editable component

src-tauri/src/instance/helpers/modpack/curseforge.rs, src-tauri/src/resource/helpers/curseforge/misc.rs, src-tauri/src/resource/helpers/modrinth/misc.rs, src-tauri/src/resource/models.rs
…API docs
fix #965
把部分数据结构的细节调整为和官方 api 的一致，尽量减少因为数据类型不匹配导致的报错
#965 的问题是某个数据成员可以为 null 但是我没写 Option<>，我对照文档检查了一遍其他的结构，把潜在的问题也修了下
=> refactor(backend): update resource data structures to match official API docs

src/components/common/option-item.tsx, src/components/instances-view.tsx, src/components/modals/download-specific-resource-modal.tsx, src/components/modals/mod-info-modal.tsx, src/components/resource-downloader.tsx, src/pages/instances/details/[id]/mods.tsx, src/pages/settings/download.tsx, src/pages/settings/general.tsx, src/pages/settings/java.tsx
close #971, close #972, close #982
关键界面截图如下：
=> fix(frontend): fix truncated text and shrunken buttons while removing unnecessary property

src-tauri/src/resource/helpers/curseforge/mod.rs, src-tauri/src/resource/helpers/modrinth/mod.rs, src/components/modals/check-mod-update-modal.tsx
close #1000 
close #974 
- 1000 的问题在 issue 里面略微解释了，这里做的修改类似于 PCL 的处理，sha1 值必须严格匹配才会正常返回
- 974 这个问题就是忘了加 mod name 和 version 没检测出来的 fallback
=> fix(resource): improve mod update modal display logic, improve SHA1 verification for resource matching

src-tauri/src/instance/helpers/options_txt.rs
=> fix(backend): fix incorrect logic in get_zh_hans_lang_tag

src/locales/en.json
=> fix: fix MUA url can not opened in English

src/locales/zh-Hant.json
=> imp: optimize traditional chinese minecraft wiki links

src-tauri/src/launcher_config/helpers/java.rs
=> feat(java): add more java vendors

src-tauri/src/launch/commands.rs
Set process priority early to enhance user experience. Ensure the startup process also utilizes a higher process priority. (If set to high)
=> imp(launch): Set process priority in advance

src/components/modals/check-mod-update-modal.tsx
=> fix(frontend): fix check mod update modal color not applied correctly in dark mode

src/contexts/global-data.tsx, src/contexts/instance.tsx, src/hooks/get-state.ts, src/pages/instances/details/[id]/worlds.tsx
close #976
分离 instanceSummary 和 instanceId，保证数据一致性（instanceId 与 page component 的 key 一致）。
~~注意：instanceSummary 等状态慢一拍，可能导致部分页面闪烁，此问题若严重，则后续再想办法修复。~~
已修复
=> refactor instance id in context

src-tauri/src/resource/helpers/misc.rs
> - fix a bug in forge bmclapi download
=> fix(download): fix a bug in forge bmclapi download

src-tauri/src/instance/helpers/loader/forge.rs, src-tauri/src/instance/helpers/loader/neoforge.rs, src-tauri/src/instance/helpers/modpack/curseforge.rs, src-tauri/src/instance/helpers/modpack/modrinth.rs
=> fix(instance): use mangled_name instead of enclosed_name to prevent zipslip
